### PR TITLE
add nightmare test

### PR DESCRIPTION
**Pull request by SimonLab**
initialise tests with nightmare see #817

### CODE REVIEW

**Comment by Jbarget** [comment]
strange i had issues with the nightmare test, could you post me the result of `server.uri.info`?

**Comment by sohilpandya** [comment]
screen shot 2017-05-23 at 11 39 03

@Jbarget here is the result 
```
http://sohils-MBP.lan:60937
```

**Comment by sohilpandya** [comment]
@Jbarget any luck? can we merge this one in? 👍

**Comment by Jbarget** [comment]
still having the same problem
1. theres an unhandled error in the nightmare test (need to add a `catch`) - i think do that regardless
2. theres the error specific to me that i can't figure out 😕

**Comment by Jbarget** [comment]
@nelsonic if you have time, would you be able to try running the test (comment out others) with:
- redis connection open: `redis-server`
- postgres connection open
- app started `npm start`

dont worry if not, just trying to narrow this bug down

**Comment by nelsonic** [comment]
@Jbarget I've added a task to test this out in my _next_ Pomodoro. 👍

**Comment by nelsonic** [comment]
@Jbarget ran the following commands on my machine:
```
git pull
git checkout nightmare-testing
npm install   # to get any new dependencies
npm test
```
Got:
```
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:88:11)
    at Object.urlParse [as parse] (url.js:82:5)
    at Object.<anonymous> (/dwyl/ce100-app/server/config.js:9:235)
``
![image](https://cloud.githubusercontent.com/assets/194400/26412559/0edbc24c-40a1-11e7-8d8c-262ef8c81435.png)

**Comment by Jbarget** [comment]
thanks @nelsonic seems like a config issue, might be coming from [this](https://github.com/emfoundation/ce100-app/blob/nightmare-testing/server/config.js#L6) line.

sorry i joined the party late, do you have `.env` with ENV variables?

**Comment by nelsonic** [comment]
@Jbarget I have an `.env` file for the project but apparently I don't have _all_ the necessary vars.
Have they been updated in the Google Doc?

**Comment by Jbarget** [comment]
not sure whether they've been updated, but might be worth copy and pasting from the google doc again

**Comment by nelsonic** [comment]
@Jbarget what is the `DATABASE_URL` you are using on your `localhost`? (_please/thanks_!)

**Comment by Jbarget** [comment]
```
DATABASE_URL=postgres://justenbarget:@localhost:5432/ce100
DATABASE_URL_TEST=postgres://justenbarget:@localhost:5432/ce100_test
```

**Comment by nelsonic** [comment]
@Jbarget thanks. 👍 
With the _latest_ Environment Variables from the Google Doc I get:
image

**Comment by Jbarget** [comment]
@SimonLab @sohilpandya it seems `server.info.uri` might not be a reliable way of assigning the base url for the test

**Comment by Jbarget** [comment]
@nelsonic if you hard code `http://localhost:3000` instead of `server.info.uri` it should work

**Comment by nelsonic** [comment]
@Jbarget is that to fix the (node:11447) UnhandledPromiseRejectionWarning ?
image

**Comment by sohilpandya** [comment]
See that's the strange thing. I haven't had to change it from server.info.uri to get it to run on my computer. 

Is the environment variable set to local host:3000 as well?

**Comment by Jbarget** [comment]
@sohilpandya @nelsonic its now working for me without any changes... 😕

**Comment by Jbarget** [comment]
Double checked by locally deleting the `nightmare-testing` branch and checking out to it again.

All tests passed, @nelsonic shall we aim to fix it on yours before merging or are you happy for us to merge this in?

**Comment by nelsonic** [comment]
@Jbarget / @sohilpandya tests _magically_ working is _undesirable_. 
But if they are working on _both_ of your machines and on CI `then` we can _proceed_. 👍

**Comment by Jbarget** [comment]
haha completely :)
will merge in and if it pops up again we'll address

**Pull request merged**
