### PR TITLE
Piggybacking #112 into master

### PR DESCRIPTION
**Pull request by mk4111**
#112 was merged into refactor-tests.
To make sure master is up to date with this, this PR request is being open to be merged into master.

### CODE REVIEW

**Comment by mk4111** [comment]
Hi @nelsonic! I've made a new PR into master. No changes have been made since #112 was merged in. If you could merge this in, that would be great! Thank you!

**Comment by nelsonic** [comment]
@mk4111 _really_ sorry to give you more work, but can you please resolve the merge conflicts for this should be limited to `routes.js` and `handlers.js` ... thanks!

**Comment by mk4111** [comment]
@nelsonic noooo problem! I'm on it!

**Comment by mk4111** [comment]
Hi @nelsonic - sorry it took some time, there were quite a few merge conflicts. Fixed now though! Yippeeeee :) If you could have a wee look and merge this in, we'd really appreciate it! Thank you!

**Comment by JMurphyWeb** [comment]
@mk4111 i'm happy to go over this branch and apply any changes to our current master branch, as I think/hope it will be quicker than merging in. Either way maybe we can go over it later today so you can talk me through our new handlers 👍

**Comment by mk4111** [comment]
@JMurphyWeb - this is the 'same' PR ( #112)  that @nelsonic merged in --> he [asked me](https://github.com/emfoundation/ce100-app/pull/112#issuecomment-246499405) to create a new PR into _master_ as #112 was merged into the _refactor-tests_ branch.

**Comment by nelsonic** [comment]
@mk4111 please fix merge conflicts so I can review/merge. thanks! 👍

**Comment by JMurphyWeb** [comment]
@mk4111 @nelsonic i am working on implementing these changes into #145 .

**Comment by mk4111** [comment]
@JMurphyWeb - quick thought - could you not take the handlers that you were working on and put those into files? Surely that would overcome the issue of loads of merge conflicts?

**Comment by JMurphyWeb** [comment]
> @JMurphyWeb - quick thought - could you not take the handlers that you were working on and put those into files? Surely that would overcome the issue of loads of merge conflicts?

In the end i changed quite a few of the handlers because the pre task todo list covered quite a few small things.

**Comment by JMurphyWeb** [comment]
@mk4111 what are your thoughts on closing this pr for now? There is #155 open for discussion and if we keep the branch then we can always refer back if/when implementing.

**Comment by JMurphyWeb** [comment]
Unless there are some features that you want to get into master branch.. Maybe we could make a different smaller pr for those changes?

**Pull request closed without merging**
