### PR TITLE
Refactor tests to reduce interaction with redis client

### PR DESCRIPTION
**Pull request by JMurphyWeb**
@nelsonic this PR has the most up to date features and tests. The tests should interact with the client less than the previous ones.

It contains almost all of our existing code, so it is probably quite big. Really sorry about this (size), won't happen again. PRs https://github.com/emfoundation/ce100-app/pull/64 & https://github.com/emfoundation/ce100-app/pull/68 probably make up the bulk of the functionality so size will reduce once those are merged in. We thought it would be good to offer you the up-to-date branch incase you would prefer to review in one big lot.

Questions:
1. Every test file requires the client purely to be able to flush the db. How do you go about flushing the db when using redis connection? does hapi-redis-connection expose the client for this purposes?  Or is there a better pattern to follow in order to flush the db?
2. Every test file uses a teardown and a tape.onfinish containing process.exit.  We want to find an alternative nicer solution to this but hope it may be easier once we have removed the client from the tests.

Todos:
- [x] Remove commented out test in admin-adds-org.js and replace with clientless assertion
- [x] Fix forceful and unnecessary teardown/onfinish on each test file (awaiting response)
- [x] Add a test /login for a user that doesn't exist.

### CODE REVIEW

**Comment by JMurphyWeb** [comment]
To clarify tests pass locally but we are having an issue with travis

**Comment by nelsonic** [comment]
@JMurphyWeb I'm _investigating now_. ⌛

**Comment by nelsonic** [comment]
@JMurphyWeb https://travis-ci.org/emfoundation/ce100-app/jobs/157747780#L482 ...

**Comment by nelsonic** [comment]
@JMurphyWeb did you _remove_ `iron` from `dependencies` in `package.json`...?
iron-removed

it's still being `require`d in `/server/handlers.js` ... https://github.com/emfoundation/ce100-app/blob/52fd252d14cc6fcaec2994be9c2f9472bc1914f7/server/handlers.js#L36

**Comment by nelsonic** [comment]
password-required-error-unclear

**Comment by JMurphyWeb** [comment]
They pass fine still. I don't remember removing iron from package json but will check my commits

**Comment by nelsonic** [comment]
@JMurphyWeb are you _sure_ you are on the `refactor-tests` branch?
The latest commit on the branch: https://github.com/emfoundation/ce100-app/blob/52fd252d14cc6fcaec2994be9c2f9472bc1914f7/package.json does not have `iron` in it and yet it's `require`'d in https://github.com/emfoundation/ce100-app/blob/52fd252d14cc6fcaec2994be9c2f9472bc1914f7/server/handlers.js#L3 so it's **_impossible_** that the tests would pass. 
image

**Comment by JMurphyWeb** [comment]
I know. I am on the right branch, and Marie has just done the same... Iron is a dependency of other modules, could it be that my `require('iron')` locates it through one of those?

Does it pass locally with you?

**Comment by nelsonic** [comment]
@JMurphyWeb ah... ok. a _nested_ dependency. Let's fix this by _specifying_ only node.js v6+ in the `package.json` to avoid any further confusion. 
(_Node V6 "flattens" out the dependency hierarchy so child/grand-child dependencies are **implicitly** available..._)

**Comment by JMurphyWeb** [comment]
@nelsonic  i am about to implement JWT2.

**Comment by nelsonic** [comment]
@JMurphyWeb & @mk4111 please have a look through the code in this PR. 
I added the auth code we paired on today and added tests.
I commented out the demo code that did not have tests.
please re-base your branches on master and continue. 👍 

❤️ ✅

**Pull request merged**
