### PR TITLE
Start on CSS for Explore views

### PR DESCRIPTION
**Pull request by mk4111**
See #327 

Updates the container for the contents of the Explore view (which affects Organisations, Challenges and Insights views) so that they take up the whole desktop width. Same for the toggle navbar in Explore views.

### CODE REVIEW

**Comment by SimonLab** [comment]
@mk4111 could you rebase one last time to include the last css from master and check that nothing has been broken? I'll try on my side too, thanks

**Comment by mk4111** [comment]
@SimonLab - I see one little issue! Can I push up again?

**Comment by SimonLab** [comment]
Looks good, just one small change on the mobile view on the challenges explore, could we delete the double lines?
challenges-view-mobile

**Comment by mk4111** [comment]
@SimonLab I'm going to go eat dinner now but will check back in an hour or so!

**Comment by SimonLab** [comment]
@mk4111 let me know when it's ready to review, you can reassign me also, thanks

**Comment by mk4111** [comment]
YAY!!! I will switch off for the evening in that case!! :D :D :D

**Pull request merged**
