### PR TITLE
Implement cancel x icon

### LINKED ISSUE #187: Remove 'cancel' buttons and replace with 'x' in header
As a user, I don't want to have a 'cancel' button right next to the 'Save' button as I may click this accidentally and lose all my data.

This should be a 'x' near the top of the page:
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=57cdad239561cc384a69e7de
emf-ce100-cancel-button-cross

### PR DESCRIPTION
**Pull request by JMurphyWeb**
To be merged after all of harry's changes.

resolves #187

### CODE REVIEW

**Comment by nelsonic** [comment]
@JMurphyWeb please re-base this branch on `master` to reduce the diff down to _only_ the feature described in the PR desc. thanks! 👍

**Comment by JMurphyWeb** [comment]
Done 👍

**Comment by nelsonic** [comment]
@JMurphyWeb _almost_ there... thanks for rebasing, please make sure travis is happy then re-assign. thanks!

**Comment by nelsonic** [comment]
@JMurphyWeb looks like we need to _verify_ the AWS account to increase SES sending limit... https://travis-ci.org/emfoundation/ce100-app/builds/163040098#L1189

**Comment by JMurphyWeb** [comment]
hmmm ah yeah Marie spotted this earlier today.. Perhaps we can fix it later?

**Comment by nelsonic** [comment]
@JMurphyWeb let me know when you have time. 👍

**Comment by nelsonic** [comment]
@JMurphyWeb I refreshed the Travis Build. ♻️ 
Tests pass. code is good. Let's add an issue to Backlog sort out SES today. (_Thanks_) 👍 
❤️ ✅ 🎉

**Pull request merged**
