### PR TITLE
active the right item when exploring orgs and challenges

### PR DESCRIPTION
**Pull request by SimonLab**
see #836

### CODE REVIEW

**Comment by Jbarget** [comment]
screen shot 2017-05-22 at 10 19 32

is this desired functionality:

1. click any "+ Add" option 
2. Hover over Explore

both options are highlighted with the light blue underline,
also, if you hover over "+ Add" when "+ Add" is highlighted the underline goes away

**Comment by SimonLab** [comment]
the hover style and the active style are the same at the moment so it is normal that if you are on the add page and you hover the explore menu both will have the blue underline.
You are right about the bug when we hover the add item the underline shouldn't disappear.

**Comment by Jbarget** [comment]
@SimonLab happy to merge this in if you could add an issue to the backlog referring to "when we hover the add item the underline shouldn't disappear"

**Comment by SimonLab** [comment]
Jbarget I have create the new issue here #846

**Comment by sohilpandya** [comment]
@Jbarget could you explain this a bit further? 

I have selected Add as a primary user, or any of the 3 options as an admin and I get the `add` item highlighted correctly, now if a user hovers over the explore it highlights the explore option as well. 

I don't see an issue here, isn't this how hover works? Here is an example of the same happening on youtube.com ( I was on home tab and hovered over trending tab)
screen shot 2017-05-22 at 12 54 23

Would love some more detail on this 😄 

The issue with the highlight going away is definitely an issue though. 👍

**Comment by Jbarget** [comment]
@sohilpandya theres nothing more to explain really, you described exactly as is :)

It was more a question whether that was desired functionality rather than flagging up a bug.

I guess to me it might have looked a bit strange as the effect of hovering over an option and show the user the `active` option show the same thing, so in the picture above its one long line under the options whereas youtube shows 2 distinct options with padding in between and the `active` one is bolder font

**Comment by sohilpandya** [comment]
Cool, can raise it in the attached issue and see if we would like the design to replicate the one shown in YT. 👍

**Pull request merged**
