### PR TITLE
Error message

### LINKED ISSUE #214: confirm password validation
```
module.exports = {
  payload: {
    password: Joi.string().min(1).required(),
    confirmPassword: Joi.string().min(1).required()
    // TODO: make min 6 & password match confirmPassword
  }
};
```

This task is still outstanding

### LINKED ISSUE #231: change to confirmPassword structure
We were storing the confirm password value in a key named `confirmPassword`.  For consistency and ease of converting into a more user friendly name, i have renamed it `confirm_password`.

I just wanted to document.

### PR DESCRIPTION
**Pull request by JMurphyWeb**
Goes a long way toward #32
Redis errors will still throw an unfriendly error but any change to this can be done in a further PR.
 
resolves #231 
resolves #214

In this PR i have added client friendly error handling for bad login credentials and failing validation at all routes that we run validation on.

### CODE REVIEW

**Comment by mk4111** [comment]
:eyes:

**Comment by nelsonic** [comment]
@JMurphyWeb please fix merge conflicts on this branch then re-assign to me. thanks! 👍

**Comment by nelsonic** [comment]
👀

**Comment by nelsonic** [comment]
@JMurphyWeb looks _really_ good. Nice work! 👍 
❤️  ✅  🎉

**Pull request merged**
